/*
SELECT
SUM(CITY.POPULATION)
FROM CITY
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE UCASE(COUNTRY.CONTINENT) = 'ASIA'
;
*/
SELECT SUM(A.POPULATION) 
FROM CITY A 
JOIN COUNTRY B ON A.COUNTRYCODE = B.CODE 
WHERE B.CONTINENT='ASIA'
;